/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAttachmentRequestDto { 
    entityType: CreateAttachmentRequestDto.EntityTypeEnum;
    entityId?: number | null;
    path?: string | null;
}
export namespace CreateAttachmentRequestDto {
    export type EntityTypeEnum = 'PARTY.COVER' | 'USER.PROFILE' | 'CLUB.COVER' | 'CLUB.PROFILE';
    export const EntityTypeEnum = {
        PartyCover: 'PARTY.COVER' as EntityTypeEnum,
        UserProfile: 'USER.PROFILE' as EntityTypeEnum,
        ClubCover: 'CLUB.COVER' as EntityTypeEnum,
        ClubProfile: 'CLUB.PROFILE' as EntityTypeEnum
    };
}


