/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBaseDto } from './userBaseDto';
import { RoleBaseDto } from './roleBaseDto';
import { ClubBaseDto } from './clubBaseDto';
import { ProfileImageDto } from './profileImageDto';


/**
 * @type CreatePartyParticipationRequestDtoUser
 * @export
 */
export type CreatePartyParticipationRequestDtoUser = UserBaseDto | number;

