/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBaseDto } from './userBaseDto';
import { VisualizationBaseDto } from './visualizationBaseDto';
import { StoryBaseDto } from './storyBaseDto';
import { PartyBaseDto } from './partyBaseDto';
import { AttachmentBaseDto } from './attachmentBaseDto';


/**
 * @type CreateVisualizationRequestDtoStory
 * @export
 */
export type CreateVisualizationRequestDtoStory = StoryBaseDto | number;

