/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductBaseDto } from './productBaseDto';
import { ProductCategoryBaseDto } from './productCategoryBaseDto';


export interface MostSoldItemDto { 
    product: ProductBaseDto;
    category: ProductCategoryBaseDto;
    amount: number;
    count: number;
}

