/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WarehouseBaseDto } from './warehouseBaseDto';
import { AddressBaseDto } from './addressBaseDto';
import { UserBaseDto } from './userBaseDto';
import { ClubBaseDtoSocialsValueValue } from './clubBaseDtoSocialsValueValue';
import { ClubBaseDto } from './clubBaseDto';
import { PartyBaseDto } from './partyBaseDto';
import { AttachmentBaseDto } from './attachmentBaseDto';


/**
 * @type PatchAddressRequestDtoClub
 * @export
 */
export type PatchAddressRequestDtoClub = ClubBaseDto | number;

