/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatchAddressRequestDtoClub } from './patchAddressRequestDtoClub';


export interface PatchAddressRequestDto { 
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    street?: string | null;
    streetNumber?: string | null;
    zipCode?: string | null;
    city?: string | null;
    country?: string | null;
    formattedAddress?: string | null;
    lat?: number | null;
    lng?: number | null;
    club?: PatchAddressRequestDtoClub | null;
}

