/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressBaseDto } from './addressBaseDto';
import { ClubBaseDto } from './clubBaseDto';
import { PartyBaseDto } from './partyBaseDto';
import { AttachmentBaseDto } from './attachmentBaseDto';


/**
 * @type PatchSavedPartyRequestDtoParty
 * @export
 */
export type PatchSavedPartyRequestDtoParty = PartyBaseDto | number;

