/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatchSavedPartyRequestDtoUser } from './patchSavedPartyRequestDtoUser';
import { Subscription } from './subscription';


export interface PatchSubscriptionRequestDto { 
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    data?: Subscription | null;
    user?: PatchSavedPartyRequestDtoUser | null;
}

