/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchAttachmentRequestDto { 
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    entityId: number | null;
    path: string;
}

