/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateAddressRequestDtoClub } from './createAddressRequestDtoClub';


export interface UpdateAddressRequestDto { 
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    street: string;
    streetNumber: string;
    zipCode: string;
    city: string;
    country: string;
    formattedAddress: string | null;
    lat: number | null;
    lng: number | null;
    club: CreateAddressRequestDtoClub;
}

