/**
 * 
 * Easydance
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBaseDto } from './userBaseDto';
import { ClubBaseDto } from './clubBaseDto';


export interface UserClubRelationBaseDto { 
    id?: number;
    uuid?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    createdBy?: string | null;
    updatedBy?: string | null;
    deletedBy?: string | null;
    club: ClubBaseDto;
    user: UserBaseDto;
    role: UserClubRelationBaseDto.RoleEnum;
}
export namespace UserClubRelationBaseDto {
    export type RoleEnum = 'CLUB_OWNER' | 'STAFF_INGRESS' | 'STAFF_STEWARD' | 'STAFF_WAITER' | 'INHERIT_USER';
    export const RoleEnum = {
        ClubOwner: 'CLUB_OWNER' as RoleEnum,
        StaffIngress: 'STAFF_INGRESS' as RoleEnum,
        StaffSteward: 'STAFF_STEWARD' as RoleEnum,
        StaffWaiter: 'STAFF_WAITER' as RoleEnum,
        InheritUser: 'INHERIT_USER' as RoleEnum
    };
}


