/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressControllerCreateDefaultResponse } from '../model/models';
import { AddressControllerFindAllDefaultResponse } from '../model/models';
import { AddressControllerFindOneDefaultResponse } from '../model/models';
import { AddressControllerReplaceDefaultResponse } from '../model/models';
import { AddressControllerUpdateDefaultResponse } from '../model/models';
import { CreateAddressRequestDto } from '../model/models';
import { PatchAddressRequestDto } from '../model/models';
import { UpdateAddressRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AddressServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createAddressRequestDto 
     * @param fields 
     * @param includes 
     */
    create(createAddressRequestDto: CreateAddressRequestDto, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<AddressControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<AddressControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     */
    findOne(id: any, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<AddressControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateAddressRequestDto 
     */
    replace(id: number, updateAddressRequestDto: UpdateAddressRequestDto, extraHttpRequestParams?: any): Observable<AddressControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchAddressRequestDto 
     */
    update(id: number, patchAddressRequestDto: PatchAddressRequestDto, extraHttpRequestParams?: any): Observable<AddressControllerUpdateDefaultResponse>;

}
