export * from './address.service';
import { AddressService } from './address.service';
export * from './address.serviceInterface';
export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './attachment.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './club.service';
import { ClubService } from './club.service';
export * from './club.serviceInterface';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './default.serviceInterface';
export * from './facebookClubLinks.service';
import { FacebookClubLinksService } from './facebookClubLinks.service';
export * from './facebookClubLinks.serviceInterface';
export * from './facebookEvents.service';
import { FacebookEventsService } from './facebookEvents.service';
export * from './facebookEvents.serviceInterface';
export * from './language.service';
import { LanguageService } from './language.service';
export * from './language.serviceInterface';
export * from './party.service';
import { PartyService } from './party.service';
export * from './party.serviceInterface';
export * from './partyParticipation.service';
import { PartyParticipationService } from './partyParticipation.service';
export * from './partyParticipation.serviceInterface';
export * from './priceListItem.service';
import { PriceListItemService } from './priceListItem.service';
export * from './priceListItem.serviceInterface';
export * from './product.service';
import { ProductService } from './product.service';
export * from './product.serviceInterface';
export * from './role.service';
import { RoleService } from './role.service';
export * from './role.serviceInterface';
export * from './savedParty.service';
import { SavedPartyService } from './savedParty.service';
export * from './savedParty.serviceInterface';
export * from './story.service';
import { StoryService } from './story.service';
export * from './story.serviceInterface';
export * from './storyLike.service';
import { StoryLikeService } from './storyLike.service';
export * from './storyLike.serviceInterface';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './subscription.serviceInterface';
export * from './table.service';
import { TableService } from './table.service';
export * from './table.serviceInterface';
export * from './tableCategory.service';
import { TableCategoryService } from './tableCategory.service';
export * from './tableCategory.serviceInterface';
export * from './tableOrder.service';
import { TableOrderService } from './tableOrder.service';
export * from './tableOrder.serviceInterface';
export * from './tableOrderRow.service';
import { TableOrderRowService } from './tableOrderRow.service';
export * from './tableOrderRow.serviceInterface';
export * from './tablePartyRule.service';
import { TablePartyRuleService } from './tablePartyRule.service';
export * from './tablePartyRule.serviceInterface';
export * from './tableReservation.service';
import { TableReservationService } from './tableReservation.service';
export * from './tableReservation.serviceInterface';
export * from './tag.service';
import { TagService } from './tag.service';
export * from './tag.serviceInterface';
export * from './translation.service';
import { TranslationService } from './translation.service';
export * from './translation.serviceInterface';
export * from './user.service';
import { UserService } from './user.service';
export * from './user.serviceInterface';
export * from './userToClubFollower.service';
import { UserToClubFollowerService } from './userToClubFollower.service';
export * from './userToClubFollower.serviceInterface';
export * from './userToUserFollower.service';
import { UserToUserFollowerService } from './userToUserFollower.service';
export * from './userToUserFollower.serviceInterface';
export * from './visualization.service';
import { VisualizationService } from './visualization.service';
export * from './visualization.serviceInterface';
export * from './warehouse.service';
import { WarehouseService } from './warehouse.service';
export * from './warehouse.serviceInterface';
export const APIS = [AddressService, AttachmentService, AuthService, ClubService, DefaultService, FacebookClubLinksService, FacebookEventsService, LanguageService, PartyService, PartyParticipationService, PriceListItemService, ProductService, RoleService, SavedPartyService, StoryService, StoryLikeService, SubscriptionService, TableService, TableCategoryService, TableOrderService, TableOrderRowService, TablePartyRuleService, TableReservationService, TagService, TranslationService, UserService, UserToClubFollowerService, UserToUserFollowerService, VisualizationService, WarehouseService];
