/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressControllerCountDefaultResponse } from '../model/models';
import { AttachmentControllerFindAllDefaultResponse } from '../model/models';
import { AttachmentControllerFindOneDefaultResponse } from '../model/models';
import { AttachmentControllerReplaceDefaultResponse } from '../model/models';
import { AttachmentControllerUpdateDefaultResponse } from '../model/models';
import { AttachmentControllerUploadFileDefaultResponse } from '../model/models';
import { CreateAttachmentRequestDto } from '../model/models';
import { PatchAttachmentRequestDto } from '../model/models';
import { UpdateAttachmentRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AttachmentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    count(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AddressControllerCountDefaultResponse>;

    /**
     * 
     * 
     * @param createAttachmentRequestDto 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    create(createAttachmentRequestDto: CreateAttachmentRequestDto, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AttachmentControllerUploadFileDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AttachmentControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findOne(id: any, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AttachmentControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateAttachmentRequestDto 
     */
    replace(id: number, updateAttachmentRequestDto: UpdateAttachmentRequestDto, extraHttpRequestParams?: any): Observable<AttachmentControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchAttachmentRequestDto 
     */
    update(id: number, patchAttachmentRequestDto: PatchAttachmentRequestDto, extraHttpRequestParams?: any): Observable<AttachmentControllerUpdateDefaultResponse>;

    /**
     * 
     * 
     * @param entityType 
     * @param entityId 
     * @param path 
     */
    uploadFile(entityType: string, entityId?: number, path?: string, extraHttpRequestParams?: any): Observable<AttachmentControllerUploadFileDefaultResponse>;

}
