/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ClubControllerCreateDefaultResponse } from '../model/models';
import { ClubControllerFindAllDefaultResponse } from '../model/models';
import { ClubControllerFindOneDefaultResponse } from '../model/models';
import { ClubControllerReplaceDefaultResponse } from '../model/models';
import { ClubControllerUpdateDefaultResponse } from '../model/models';
import { CreateClubRequestDto } from '../model/models';
import { CurrentParty } from '../model/models';
import { PatchClubRequestDto } from '../model/models';
import { UpdateClubRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClubServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createClubRequestDto 
     * @param fields 
     * @param includes 
     */
    create(createClubRequestDto: CreateClubRequestDto, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<ClubControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<ClubControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     */
    findOne(id: any, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<ClubControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param club 
     */
    getCurrentParty(club: number, extraHttpRequestParams?: any): Observable<CurrentParty>;

    /**
     * 
     * 
     * @param id 
     * @param updateClubRequestDto 
     */
    replace(id: number, updateClubRequestDto: UpdateClubRequestDto, extraHttpRequestParams?: any): Observable<ClubControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchClubRequestDto 
     */
    update(id: number, patchClubRequestDto: PatchClubRequestDto, extraHttpRequestParams?: any): Observable<ClubControllerUpdateDefaultResponse>;

}
