/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeocodeResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    get(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getHello(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param search 
     */
    googleGeocoding(search: string, extraHttpRequestParams?: any): Observable<GeocodeResponse>;

    /**
     * 
     * 
     * @param lat 
     * @param lng 
     */
    googleGeocodingReverse(lat: string, lng: string, extraHttpRequestParams?: any): Observable<GeocodeResponse>;

    /**
     * 
     * 
     */
    notify(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param pwd 
     */
    vapId(pwd: string, extraHttpRequestParams?: any): Observable<{}>;

}
