/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateFacebookEventsRequestDto } from '../model/models';
import { FacebookEventsControllerCreateDefaultResponse } from '../model/models';
import { FacebookEventsControllerFindAllDefaultResponse } from '../model/models';
import { FacebookEventsControllerFindOneDefaultResponse } from '../model/models';
import { FacebookEventsControllerReplaceDefaultResponse } from '../model/models';
import { FacebookEventsControllerUpdateDefaultResponse } from '../model/models';
import { PatchFacebookEventsRequestDto } from '../model/models';
import { UpdateFacebookEventsRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FacebookEventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createFacebookEventsRequestDto 
     * @param fields 
     * @param includes 
     */
    create(createFacebookEventsRequestDto: CreateFacebookEventsRequestDto, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<FacebookEventsControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param createFacebookEventsRequestDto 
     */
    createMany(createFacebookEventsRequestDto: Array<CreateFacebookEventsRequestDto>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<FacebookEventsControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     */
    findOne(id: any, fields?: string, includes?: string, extraHttpRequestParams?: any): Observable<FacebookEventsControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateFacebookEventsRequestDto 
     */
    replace(id: number, updateFacebookEventsRequestDto: UpdateFacebookEventsRequestDto, extraHttpRequestParams?: any): Observable<FacebookEventsControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchFacebookEventsRequestDto 
     */
    update(id: number, patchFacebookEventsRequestDto: PatchFacebookEventsRequestDto, extraHttpRequestParams?: any): Observable<FacebookEventsControllerUpdateDefaultResponse>;

}
