/**
 * 
 * Easydance
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressControllerCountDefaultResponse } from '../model/models';
import { CreatePartyJoinerRequestDto } from '../model/models';
import { PartyJoinerControllerCreateDefaultResponse } from '../model/models';
import { PartyJoinerControllerFindAllDefaultResponse } from '../model/models';
import { PartyJoinerControllerFindOneDefaultResponse } from '../model/models';
import { PartyJoinerControllerSetDefaultResponse } from '../model/models';
import { PartyJoinerControllerUpdateDefaultResponse } from '../model/models';
import { PatchPartyJoinerRequestDto } from '../model/models';
import { UpdatePartyJoinerRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PartyJoinerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    count(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AddressControllerCountDefaultResponse>;

    /**
     * 
     * 
     * @param createPartyJoinerRequestDto 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    create(createPartyJoinerRequestDto: CreatePartyJoinerRequestDto, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<PartyJoinerControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param ids 
     */
    deleteMany(ids: Array<number>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<PartyJoinerControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findOne(id: any, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<PartyJoinerControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updatePartyJoinerRequestDto 
     */
    replace(id: number, updatePartyJoinerRequestDto: UpdatePartyJoinerRequestDto, extraHttpRequestParams?: any): Observable<PartyJoinerControllerSetDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     */
    restore(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updatePartyJoinerRequestDto 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    set(updatePartyJoinerRequestDto: UpdatePartyJoinerRequestDto, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<PartyJoinerControllerSetDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchPartyJoinerRequestDto 
     */
    update(id: number, patchPartyJoinerRequestDto: PatchPartyJoinerRequestDto, extraHttpRequestParams?: any): Observable<PartyJoinerControllerUpdateDefaultResponse>;

}
