/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRoleRequestDto } from '../model/models';
import { PatchRoleRequestDto } from '../model/models';
import { RoleControllerCreateDefaultResponse } from '../model/models';
import { RoleControllerFindAllDefaultResponse } from '../model/models';
import { RoleControllerFindOneDefaultResponse } from '../model/models';
import { RoleControllerReplaceDefaultResponse } from '../model/models';
import { RoleControllerUpdateDefaultResponse } from '../model/models';
import { UpdateRoleRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createRoleRequestDto 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    create(createRoleRequestDto: CreateRoleRequestDto, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<RoleControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<RoleControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findOne(id: any, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<RoleControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateRoleRequestDto 
     */
    replace(id: number, updateRoleRequestDto: UpdateRoleRequestDto, extraHttpRequestParams?: any): Observable<RoleControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchRoleRequestDto 
     */
    update(id: number, patchRoleRequestDto: PatchRoleRequestDto, extraHttpRequestParams?: any): Observable<RoleControllerUpdateDefaultResponse>;

}
