/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSavedPartyRequestDto } from '../model/models';
import { PatchSavedPartyRequestDto } from '../model/models';
import { SavedPartyControllerCreateDefaultResponse } from '../model/models';
import { SavedPartyControllerFindAllDefaultResponse } from '../model/models';
import { SavedPartyControllerFindOneDefaultResponse } from '../model/models';
import { SavedPartyControllerReplaceDefaultResponse } from '../model/models';
import { SavedPartyControllerUpdateDefaultResponse } from '../model/models';
import { UpdateSavedPartyRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SavedPartyServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createSavedPartyRequestDto 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    create(createSavedPartyRequestDto: CreateSavedPartyRequestDto, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<SavedPartyControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<SavedPartyControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findOne(id: any, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<SavedPartyControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateSavedPartyRequestDto 
     */
    replace(id: number, updateSavedPartyRequestDto: UpdateSavedPartyRequestDto, extraHttpRequestParams?: any): Observable<SavedPartyControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchSavedPartyRequestDto 
     */
    update(id: number, patchSavedPartyRequestDto: PatchSavedPartyRequestDto, extraHttpRequestParams?: any): Observable<SavedPartyControllerUpdateDefaultResponse>;

}
