/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressControllerCountDefaultResponse } from '../model/models';
import { CreateSubscriptionRequestDto } from '../model/models';
import { PatchSubscriptionRequestDto } from '../model/models';
import { SubscriptionControllerCreateDefaultResponse } from '../model/models';
import { SubscriptionControllerFindAllDefaultResponse } from '../model/models';
import { SubscriptionControllerFindOneDefaultResponse } from '../model/models';
import { SubscriptionControllerReplaceDefaultResponse } from '../model/models';
import { SubscriptionControllerUpdateDefaultResponse } from '../model/models';
import { UpdateSubscriptionRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SubscriptionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    count(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AddressControllerCountDefaultResponse>;

    /**
     * 
     * 
     * @param createSubscriptionRequestDto 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    create(createSubscriptionRequestDto: CreateSubscriptionRequestDto, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<SubscriptionControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<SubscriptionControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findOne(id: any, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<SubscriptionControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateSubscriptionRequestDto 
     */
    replace(id: number, updateSubscriptionRequestDto: UpdateSubscriptionRequestDto, extraHttpRequestParams?: any): Observable<SubscriptionControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     */
    restore(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param patchSubscriptionRequestDto 
     */
    update(id: number, patchSubscriptionRequestDto: PatchSubscriptionRequestDto, extraHttpRequestParams?: any): Observable<SubscriptionControllerUpdateDefaultResponse>;

}
