/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTagRequestDto } from '../model/models';
import { PatchTagRequestDto } from '../model/models';
import { TagControllerCreateDefaultResponse } from '../model/models';
import { TagControllerFindAllDefaultResponse } from '../model/models';
import { TagControllerFindOneDefaultResponse } from '../model/models';
import { TagControllerReplaceDefaultResponse } from '../model/models';
import { TagControllerUpdateDefaultResponse } from '../model/models';
import { UpdateTagRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TagServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createTagRequestDto 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    create(createTagRequestDto: CreateTagRequestDto, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TagControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TagControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findOne(id: any, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TagControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateTagRequestDto 
     */
    replace(id: number, updateTagRequestDto: UpdateTagRequestDto, extraHttpRequestParams?: any): Observable<TagControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchTagRequestDto 
     */
    update(id: number, patchTagRequestDto: PatchTagRequestDto, extraHttpRequestParams?: any): Observable<TagControllerUpdateDefaultResponse>;

}
