/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTranslationRequestDto } from '../model/models';
import { PatchTranslationRequestDto } from '../model/models';
import { TranslationControllerCreateDefaultResponse } from '../model/models';
import { TranslationControllerFindAllDefaultResponse } from '../model/models';
import { TranslationControllerFindOneDefaultResponse } from '../model/models';
import { TranslationControllerReplaceDefaultResponse } from '../model/models';
import { TranslationControllerUpdateDefaultResponse } from '../model/models';
import { UpdateTranslationRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TranslationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createTranslationRequestDto 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    create(createTranslationRequestDto: CreateTranslationRequestDto, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TranslationControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TranslationControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param withDeleted 
     */
    findOne(id: any, fields?: string, includes?: string, withDeleted?: string, extraHttpRequestParams?: any): Observable<TranslationControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param language 
     */
    get(language: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     * @param updateTranslationRequestDto 
     */
    replace(id: number, updateTranslationRequestDto: UpdateTranslationRequestDto, extraHttpRequestParams?: any): Observable<TranslationControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param patchTranslationRequestDto 
     */
    update(id: number, patchTranslationRequestDto: PatchTranslationRequestDto, extraHttpRequestParams?: any): Observable<TranslationControllerUpdateDefaultResponse>;

}
