/**
 * 
 * Your api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressControllerCountDefaultResponse } from '../model/models';
import { CreateUserRequestDto } from '../model/models';
import { PatchUserRequestDto } from '../model/models';
import { UpdateUserRequestDto } from '../model/models';
import { UserControllerCreateDefaultResponse } from '../model/models';
import { UserControllerFindAllDefaultResponse } from '../model/models';
import { UserControllerFindOneDefaultResponse } from '../model/models';
import { UserControllerReplaceDefaultResponse } from '../model/models';
import { UserControllerUpdateDefaultResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    count(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<AddressControllerCountDefaultResponse>;

    /**
     * 
     * 
     * @param createUserRequestDto 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    create(createUserRequestDto: CreateUserRequestDto, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<UserControllerCreateDefaultResponse>;

    /**
     * 
     * 
     * @param createUserRequestDto 
     */
    createStaffUser(createUserRequestDto: CreateUserRequestDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param sorting 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findAll(page?: number, pageSize?: number, filters?: string, sorting?: string, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<UserControllerFindAllDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param fields 
     * @param includes 
     * @param deleted 
     */
    findOne(id: any, fields?: string, includes?: string, deleted?: string, extraHttpRequestParams?: any): Observable<UserControllerFindOneDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateUserRequestDto 
     */
    replace(id: number, updateUserRequestDto: UpdateUserRequestDto, extraHttpRequestParams?: any): Observable<UserControllerReplaceDefaultResponse>;

    /**
     * 
     * 
     * @param id 
     */
    restore(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param patchUserRequestDto 
     */
    update(id: number, patchUserRequestDto: PatchUserRequestDto, extraHttpRequestParams?: any): Observable<UserControllerUpdateDefaultResponse>;

}
