name: Copy files with SCP

on:
  push:
    branches:
      - releases
  workflow_dispatch:

jobs:

  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: dkershner6/post-api-call-action@v1
        with:
          url: https://api.easydance.app/attributes/app-version
          headers: '{"Content-Type": "application/json", "API-KEY": "1b4f951d-1fde-44a6-acf6-b22dd85902b8"}'  # Intestazioni della richiesta (JSON)
  
  copy:
    needs: [ update-version ]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build image
      run: npm i && npm run build
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r build.zip www
    - name: Publish
      uses: nogsantos/scp-deploy@master
      with:
        src: build.zip
        host: 149.62.186.238
        remote: /var/lib/docker/volumes/easydance-production_static/_data/releases
        port: 22
        user: appreleaser
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrUl4zWSs9kfZqPhd+dQyvfhpa6LuUeOCbNc0IeiShKBk/fDrYwOZRd3BYmAS6E1mDFzVNQtrZajHsHQoN2F6juMqVUYAg/gzO7WomypaYH14eKiA4hqOXHKYzyoGVmbz/TFNd5f3Hl+tRp468Trx4GcjSoSF00TXBcR1T7h9PPFuEmNopGfHKpFfL2qyG5p1TZmx4py0/Ek4E8dmrGEoPrxgbzDJnXB5vjtaXmQvCrymgFLouvYPbueK56WcLMJHmoODVLOuXknKdSTc8tTcphJGs17eYDzQqaQqKy4ryVss5GGZVwgLjr9VO+i6UPudpNEFzlDagdHTqHQfqhmUgkFr69bklSTQSY6RHqeaDF9Ip0PiFtuKkSRoS1lTLfBDNLd3d9rCbxkjYrfgq4oP1rshJn8trxhc82OyYoivSvK/QIQ8WelyZralaa1Djw8W+9RlgjoHN/ab2M93spFiWiJZTy4ql8Gr6HvCn4DyXozSXa7x9SaYgBU5oW9AOtqHB4L0gYmjnr36bUzJENA+rydGaosxb/tAQwo5kS4gQI1n2AnZOyvliyBJBr+fUS2PkhUjTT1VsFe1KyiBfufAzpCEjcIkK4SNglBf4DfgXezbOsqyTChzGKIeIAayjavF6XcvVArSxFHwUWKMJrLZrq7ykXs0/IaLgM9d5UBh6Fw== simone@oddastudio.com
